### ISSUE TITLE
Workbench port should be set as variable

### ISSUE THREAD

**Issue by anastacia-maletskaya-epam** [lean-delivery/ansible-role-endeca-toolsandframeworks#5]
##### SUMMARY

Workbench port (8006) should be set as variable because it can be used by other roles in playbooks
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

tasks/update-workbench-password.yml
##### ANSIBLE VERSION

```
2.5.8
```

##### EXPECTED RESULTS

        - name: "Change default workbench admin password"
          uri:
            url: "http://{{ ansible_hostname }}:8006\
            /ifcr/system/userManager/user/admin.changePassword.json"
            user: "{{ workbench_user }}"
            password: "{{ workbench_password_default }}"
            method: "POST"
            body: "oldPwd={{ workbench_password_default }}&newPwd={{ workbench_password }}\
            &newPwdConfirm={{ workbench_password }}"
            return_content: True
            headers:
              Content-Type: "application/x-www-form-urlencoded"
            status_code: "200"
            timeout: "300"
##### ACTUAL RESULTS

"8006" port should be set in defaults/main.yml

**Comment by ibarysev** [comment]
Merged
